language: java


script:
  - javac WordCount.java
  - java WordCount < Script.txt

notifications:
  email: false
  
deploy:  &heroku
  - provider: heroku
    script: 'git stash apply $stash_hash'
    api_key: 423bc40c-5439-4d03-b32b-2acc05f6dbe9
    app: shannabenammar-a-10
    

