language: java

git:
  depth: 3
  
# safelist
branches:
  only:
  - master
  - stable

script:
  - javac WordCount.java
  - java WordCount < Script.txt

notifications:
  email: false
  
deploy:
  - provider: heroku
    api_key: 423bc40c-5439-4d03-b32b-2acc05f6dbe9
    app: shannabenammar-a-10

